import * as THREE from "three";

const MAX_TEXTURE_LAYERS = 8;

export class Terrain {
  constructor(scene) { this.scene = scene; this.mesh = null; this.signature = ""; this.textureLoader = new THREE.TextureLoader(); this.textures = new Map(); this.placeholderTexture = new THREE.Texture(); }
  apply(config) {
    if (!config?.enabled) { this.mesh?.removeFromParent(); return; }
    const signature = `${config.size}:${config.segments}:${config.color}`;
    if (this.signature !== signature || !this.mesh) {
      this.mesh?.removeFromParent(); this.mesh?.geometry.dispose(); this.mesh?.material.dispose();
       const geometry = new THREE.PlaneGeometry(config.size, config.size, config.segments, config.segments); geometry.rotateX(-Math.PI / 2);
      const material = new THREE.MeshStandardMaterial({ color: 0xffffff, vertexColors: true, roughness: 1, metalness: 0, fog: true }); this.configureTextureBlend(material);
      this.mesh = new THREE.Mesh(geometry, material); this.mesh.name = "Terrain"; this.mesh.receiveShadow = true; this.mesh.userData.isTerrain = true; this.scene.add(this.mesh); this.signature = signature;
    }
    this.config = config; this.updateHeights(config); this.updateColors(config); this.updateTextureMasks(config); this.loadTextures(config.textures);
  }
   updateHeights(config) { const positions = this.mesh?.geometry.getAttribute("position"); if (!positions) return; for (let i = 0; i < positions.count; i++) positions.setY(i, config.heights[i] ?? 0); positions.needsUpdate = true; this.mesh.geometry.computeVertexNormals(); }
  updateColors(config) { if (!this.mesh) return; const geometry = this.mesh.geometry; let colors = geometry.getAttribute("color"); if (!colors) { colors = new THREE.BufferAttribute(new Float32Array(geometry.getAttribute("position").count * 3), 3); geometry.setAttribute("color", colors); } const color = new THREE.Color(); for (let i = 0; i < colors.count; i++) { color.setHex(config.colors[i] ?? config.color); colors.setXYZ(i, color.r, color.g, color.b); } colors.needsUpdate = true; }
  updateTextureMasks(config) { if (!this.mesh) return; const geometry = this.mesh.geometry, count = geometry.getAttribute("position").count; for (let layer = 0; layer < MAX_TEXTURE_LAYERS; layer++) { let mask = geometry.getAttribute(`terrainTextureMask${layer}`); if (!mask) { mask = new THREE.BufferAttribute(new Float32Array(count), 1); geometry.setAttribute(`terrainTextureMask${layer}`, mask); } const values = config.textures?.[layer]?.mask ?? []; for (let i = 0; i < count; i++) mask.setX(i, values[i] ?? 0); mask.needsUpdate = true; } }
  configureTextureBlend(material) {
    material.onBeforeCompile = shader => {
      // Always compile eight slots. This prevents Three.js from retaining a
      // one-texture shader program when layers are added during editing.
      const attributes = `varying vec2 vTerrainUv;\n${Array.from({ length: MAX_TEXTURE_LAYERS }, (_, i) => `attribute float terrainTextureMask${i};\nvarying float vTerrainTextureMask${i};`).join("\n")}`;
      const varyings = `varying vec2 vTerrainUv;\n${Array.from({ length: MAX_TEXTURE_LAYERS }, (_, i) => `varying float vTerrainTextureMask${i};`).join("\n")}`;
      const assignments = `vTerrainUv = uv;\n${Array.from({ length: MAX_TEXTURE_LAYERS }, (_, i) => `vTerrainTextureMask${i} = terrainTextureMask${i};`).join("\n")}`;
      const uniforms = Array.from({ length: MAX_TEXTURE_LAYERS }, (_, i) => `uniform sampler2D terrainMap${i};\nuniform float terrainMapScale${i};`).join("\n");
      // Most of the terrain only has one painted layer. Avoid sampling all
      // eight textures for every terrain fragment, especially on mobile GPUs.
      const samples = Array.from({ length: MAX_TEXTURE_LAYERS }, (_, i) => `float terrainMask${i} = vTerrainTextureMask${i}; if (terrainMask${i} > 0.0001) { vec3 terrainColor${i} = texture2D(terrainMap${i}, vTerrainUv * terrainMapScale${i}).rgb; terrainWeight += terrainMask${i}; terrainPaint += terrainColor${i} * terrainMask${i}; }`).join("\n        ");
      shader.vertexShader = shader.vertexShader.replace("#include <common>", `#include <common>\n${attributes}`).replace("#include <begin_vertex>", `${assignments}\n#include <begin_vertex>`);
      shader.fragmentShader = shader.fragmentShader.replace("#include <common>", `#include <common>\n${varyings}\n${uniforms}`).replace("#include <color_fragment>", `#include <color_fragment>\n        float terrainWeight = 0.0; vec3 terrainPaint = vec3(0.0);\n        ${samples}\n        diffuseColor.rgb = diffuseColor.rgb * max(0.0, 1.0 - terrainWeight) + terrainPaint;`);
      for (let i = 0; i < MAX_TEXTURE_LAYERS; i++) {
        shader.uniforms[`terrainMap${i}`] = { value: material.userData.terrainTextures?.[i] ?? this.placeholderTexture };
        shader.uniforms[`terrainMapScale${i}`] = { value: material.userData.terrainTextureScales?.[i] ?? 1 };
      }
      material.userData.terrainShader = shader;
    };
    material.customProgramCacheKey = () => "next-world-terrain-eight-texture-slots-v2";
  }
  configureTexture(texture, scale) { texture.colorSpace = THREE.SRGBColorSpace; texture.wrapS = texture.wrapT = THREE.RepeatWrapping; texture.repeat.set(scale, scale); texture.anisotropy = 8; return texture; }
  loadTextures(layers = []) { for (const layer of layers.slice(0, MAX_TEXTURE_LAYERS)) if (layer?.src && !this.textures.has(layer.src)) this.textureLoader.load(layer.src, texture => { this.textures.set(layer.src, this.configureTexture(texture, layer.scale)); this.applyTextures(); }, undefined, () => console.warn(`Could not load terrain texture: ${layer.src}`)); this.applyTextures(layers); }
  loadTextureFile(file, savedPath, scale = 8) { const url = URL.createObjectURL(file); this.textureLoader.load(url, texture => { URL.revokeObjectURL(url); this.textures.get(savedPath)?.dispose(); this.textures.set(savedPath, this.configureTexture(texture, scale)); this.applyTextures(); }, undefined, () => URL.revokeObjectURL(url)); }
  applyTextures(layers) { if (!this.mesh) return; const sourceLayers = layers ?? this.mesh.userData.terrainLayers ?? []; this.mesh.userData.terrainLayers = sourceLayers; const material = this.mesh.material; material.userData.terrainTextures = Array.from({ length: MAX_TEXTURE_LAYERS }, (_, i) => this.textures.get(sourceLayers[i]?.src) ?? this.placeholderTexture); material.userData.terrainTextureScales = Array.from({ length: MAX_TEXTURE_LAYERS }, (_, i) => sourceLayers[i]?.scale ?? 1); material.map = null; const shader = material.userData.terrainShader; if (!shader) { material.needsUpdate = true; return; } for (let i = 0; i < MAX_TEXTURE_LAYERS; i++) { shader.uniforms[`terrainMap${i}`].value = material.userData.terrainTextures[i]; shader.uniforms[`terrainMapScale${i}`].value = material.userData.terrainTextureScales[i]; } }
  sculpt(config, point, radius, amount, mode, flattenHeight = 0) { if (!this.mesh || radius <= 0) return false; const positions = this.mesh.geometry.getAttribute("position"), heights = config.heights, width = config.segments + 1, before = mode === "smooth" ? heights.slice() : null; let changed = false; for (let i = 0; i < positions.count; i++) { const distance = Math.hypot(positions.getX(i) - point.x, positions.getZ(i) - point.z); if (distance > radius) continue; const weight = (1 - distance / radius) ** 2; if (mode === "smooth") { const x = i % width, z = Math.floor(i / width); let total = before[i], count = 1; for (const n of [x > 0 ? i - 1 : -1, x < width - 1 ? i + 1 : -1, z > 0 ? i - width : -1, z < width - 1 ? i + width : -1]) if (n >= 0) { total += before[n]; count++; } heights[i] += (total / count - heights[i]) * Math.min(1, amount * 3) * weight; } else if (mode === "flatten") heights[i] += (flattenHeight - heights[i]) * Math.min(1, amount * 3) * weight; else heights[i] += amount * weight; changed = true; } if (changed) this.updateHeights(config); return changed; }
  paint(config, point, radius, colorHex, strength) { if (!this.mesh || radius <= 0) return false; const positions = this.mesh.geometry.getAttribute("position"), from = new THREE.Color(), target = new THREE.Color(colorHex); let changed = false; for (let i = 0; i < positions.count; i++) { const d = Math.hypot(positions.getX(i) - point.x, positions.getZ(i) - point.z); if (d > radius) continue; from.setHex(config.colors[i] ?? config.color).lerp(target, Math.min(1, strength * (1 - d / radius) ** 2)); config.colors[i] = from.getHex(); changed = true; } if (changed) this.updateColors(config); return changed; }
  paintTexture(config, point, radius, strength) { const active = config.activeTexture ?? 0, layers = config.textures ?? []; if (!this.mesh || radius <= 0 || !layers[active]?.src) return false; const positions = this.mesh.geometry.getAttribute("position"); let changed = false; for (let i = 0; i < positions.count; i++) { const d = Math.hypot(positions.getX(i) - point.x, positions.getZ(i) - point.z); if (d > radius) continue; const add = Math.min(1, strength * (1 - d / radius) ** 2), current = layers[active].mask[i] ?? 0, next = Math.min(1, current + add), reduction = Math.max(0, 1 - next) / Math.max(.0001, 1 - current); for (let layer = 0; layer < layers.length; layer++) if (layer !== active) layers[layer].mask[i] = (layers[layer].mask[i] ?? 0) * reduction; layers[active].mask[i] = next; changed = true; } if (changed) this.updateTextureMasks(config); return changed; }
  resize(config, newSize) { const oldSize = config.size, segments = config.segments, newSegments = THREE.MathUtils.clamp(Math.round(segments * newSize / oldSize), 8, 512), width = segments + 1, newWidth = newSegments + 1, oldHeights = config.heights.slice(), oldColors = config.colors.slice(), oldMasks = config.textures.map(layer => layer.mask.slice()); const sample = (values, x, z, fallback = 0) => { if (x < 0 || z < 0 || x > segments || z > segments) return fallback; return values[Math.round(z) * width + Math.round(x)] ?? fallback; }; const remap = (values, fallback) => Array.from({ length: newWidth * newWidth }, (_, i) => { const x = i % newWidth, z = Math.floor(i / newWidth), wx = (x / newSegments - .5) * newSize, wz = (z / newSegments - .5) * newSize; return sample(values, (wx / oldSize + .5) * segments, (wz / oldSize + .5) * segments, fallback); }); config.heights = remap(oldHeights, 0); config.colors = remap(oldColors, config.color); config.textures.forEach((layer, i) => { layer.mask = remap(oldMasks[i], 0); }); config.size = newSize; config.segments = newSegments; this.signature = ""; this.apply(config); }
  getHeightAt(point) { const config = this.config; if (!config) return 0; const width = config.segments + 1, gridX = THREE.MathUtils.clamp((point.x / config.size + .5) * config.segments, 0, config.segments), gridZ = THREE.MathUtils.clamp((point.z / config.size + .5) * config.segments, 0, config.segments), x0 = Math.floor(gridX), z0 = Math.floor(gridZ), x1 = Math.min(config.segments, x0 + 1), z1 = Math.min(config.segments, z0 + 1), tx = gridX - x0, tz = gridZ - z0, h00 = config.heights[z0 * width + x0] ?? 0, h10 = config.heights[z0 * width + x1] ?? 0, h01 = config.heights[z1 * width + x0] ?? 0, h11 = config.heights[z1 * width + x1] ?? 0; return THREE.MathUtils.lerp(THREE.MathUtils.lerp(h00, h10, tx), THREE.MathUtils.lerp(h01, h11, tx), tz); }
}
